"""Entry point for paper/live trading."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from stockbot.adapters.akshare_market import AkshareHistoryRequest, AkshareMarketData
from stockbot.adapters.lark_alert import LarkAlertBroker
from stockbot.adapters.paper import PaperBroker
from stockbot.adapters.qmt_xtquant import QmtAdapter
from stockbot.adapters.xtquant_market import HistoryRequest, XtQuantMarketData
from stockbot.core.config import load_config
from stockbot.core.engine import TradingEngine
from stockbot.core.models import Side, Signal
from stockbot.strategies.aggressive_growth import AggressiveGrowthStrategy
from stockbot.strategies.leader import LeaderStrategy
from stockbot.strategies.dragon_head import DragonHeadStrategy


def load_bars(cfg: dict, symbols: list[str]) -> dict[str, object]:
    provider = cfg.get("market_data", {}).get("provider", "akshare")
    if provider == "xtquant":
        return XtQuantMarketData(cfg).get_history(HistoryRequest(symbols=symbols))
    if provider == "akshare":
        return AkshareMarketData(cfg).get_history(AkshareHistoryRequest(symbols=symbols))
    raise RuntimeError(f"不支持的行情源: {provider}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="config.yaml")
    parser.add_argument("--live", action="store_true", help="use live broker mode; config must also enable runtime.enabled")
    parser.add_argument("--symbols", default="", help="comma separated A-share symbols for market data")
    parser.add_argument("--universe-file", default="", help="CSV generated by scripts/build_universe.py")
    parser.add_argument("--top", type=int, default=20, help="top symbols from universe file")
    parser.add_argument("--mock-buy", default="", help="paper mode test signal, e.g. 300750.SZ:180.50")
    args = parser.parse_args()

    cfg = load_config(Path(args.config))
    if args.live:
        cfg["runtime"]["env"] = "live"

    env = cfg["runtime"]["env"]
    if env == "live":
        broker = QmtAdapter(cfg)
        broker.connect()
    elif env == "alert":
        # macOS 实盘过渡方案:推飞书,不真下单
        broker = LarkAlertBroker(cfg)
    else:
        broker = PaperBroker(cfg)

    signals: list[Signal] = []
    strategy_name = cfg.get("runtime", {}).get("strategy", "leader")
    if strategy_name == "dragon_head":
        strategy = DragonHeadStrategy(cfg)
    elif strategy_name == "leader":
        strategy = LeaderStrategy(cfg)
    elif strategy_name == "aggressive_growth":
        strategy = AggressiveGrowthStrategy(cfg)
    else:
        raise RuntimeError(f"不支持的策略: {strategy_name}")
    symbols: list[str] = []
    universe_name_map: dict[str, str] = {}
    if args.symbols:
        symbols = [s.strip() for s in args.symbols.split(",") if s.strip()]
    elif args.universe_file:
        import pandas as pd
        universe = pd.read_csv(args.universe_file)
        universe_name_map = dict(zip(universe["symbol"].astype(str), universe["name"].astype(str))) if "name" in universe.columns else {}
        symbols = universe["symbol"].head(args.top).astype(str).tolist()
    if symbols:
        bars = load_bars(cfg, symbols)
        for symbol, df in bars.items():
            if symbol in universe_name_map:
                df["name"] = universe_name_map[symbol]
        signals.extend(strategy.generate(bars))
    if args.mock_buy:
        symbol, price_text = args.mock_buy.split(":", 1)
        signals.insert(0, Signal(symbol=symbol, side=Side.BUY, weight=1.0, reason="manual_paper_test", price=float(price_text)))

    engine = TradingEngine(cfg, broker)
    orders = engine.execute(signals)
    print(f"signals={len(signals)} accepted_orders={len(orders)}")
    for order in orders:
        print(f"{order.side.value} {order.symbol} qty={order.quantity} price={order.price} reason={order.reason}")


if __name__ == "__main__":
    main()
